# Generated by Django 5.2.4 on 2026-08-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_productimage_is_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Brand logo', null=True, upload_to='brands/images/')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/images/'),
        ),
        migrations.SeparateDatabaseAndState(
    state_operations=[
        migrations.AddField(
            model_name='productvariant',
            name='discount_percent',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Discount percentage (0-100)'
            ),
        ),
    ],
    database_operations=[],
),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
    ]
