# Generated by Django 5.2.4 on 2026-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Selected product'),
        ),
        migrations.AddField(
            model_name='products',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of sale'),
        ),
        migrations.AddField(
            model_name='products',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text=' Number of view'),
        ),
    ]
