# Generated by Django 5.2.4 on 2026-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_is_featured_products_sales_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Galaxy S24 Ultra', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Small text above the title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description under the title')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/', help_text='Button link (example: /product/1)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
